title: "Németh Dávid"
name: "Németh Dávid"
description: "Software Engineering, Machine Learning, Systems"
url: "https://ho92ms.github.io"

author:
  name: "Németh Dávid"
  email: "neduabi@pm.me"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
